CREATE TABLE testtable2 (id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, input varchar(254) NOT NULL);
insert into testtable2 (input) values ('First insert test.');
/* a comment */
/* another comment */
nsert into testtable2 (input) values ('Second insert test.');
insert into testtable2 (input) values ('Third insert test.');
ALTER TABLE testtable2 ADD COLUMN newinput VARCHAR(255);
DROP TABLE testtable2;
