CREATE TABLE rangechecktesttable (id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, input varchar(254) NOT NULL);
insert into rangechecktesttable (input) values ('First insert test.');
/* a comment */
/* another comment */
insert into rangechecktesttable (input) values ('Second insert test.');
insert into rangechecktesttable (input) values ('Third insert test.');
ALTER TABLE rangechecktesttable ADD COLUMN newinput VARCHAR(255);
DROP TABLE rangechecktesttable;